# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abe0ceac631152ba7752c244c2a454c106d820658b0300838a66599a177fc88ad788cf3a3a493848f8a9319058743ee6ba9d3d47c7cb9fd6443556a52df8f39b

test:
  secret_key_base: 53a404634baa0319c74850999cab7742199c1652035134201c50120844bf972dc9f1711033f289f46ccac7dadff8e61022cb0dd1f62081f4e313b624d7371ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
